"""Add is_buy column to roles table

Revision ID: 41336457e616
Revises: 6fdbf9369526
Create Date: 2025-12-23 14:31:31.093360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41336457e616'
down_revision: Union[str, Sequence[str], None] = '6fdbf9369526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_buy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_buy')
    # ### end Alembic commands ###
