"""Add max_inventory column to users table

Revision ID: 9f8c7d6e5a4b
Revises: 89eded433a9f
Create Date: 2025-01-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8c7d6e5a4b'
down_revision: Union[str, Sequence[str], None] = '41336457e616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_inventory', sa.Integer(), nullable=False, server_default='50'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_inventory')
    # ### end Alembic commands ###
