"""Add user_roles table with correct data types

Revision ID: f4c0b64585f3
Revises: 
Create Date: 2025-12-23 14:19:39.838229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4c0b64585f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.alter_column('active_shifts', 'start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('active_shifts', 'end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_user_id'), table_name='inventory')
    op.drop_index(op.f('unique_user_item'), table_name='inventory')
    op.create_index(op.f('ix_inventory_user_id'), 'inventory', ['user_id'], unique=False)
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'last_fight_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_fight_time',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'color')
    op.drop_column('roles', 'description')
    op.drop_index(op.f('ix_inventory_user_id'), table_name='inventory')
    op.create_index(op.f('unique_user_item'), 'inventory', ['user_id', 'item_name'], unique=True)
    op.create_index(op.f('idx_user_id'), 'inventory', ['user_id'], unique=False)
    op.alter_column('active_shifts', 'end_time',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.alter_column('active_shifts', 'start_time',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.drop_table('user_roles')
    # ### end Alembic commands ###
